# Generated by Django 3.1 on 2020-09-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmanagement',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
